name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              
            - name: install cowsay program
              run: sudo apt-get install cowsay -y
            
            - name: Execute cowsay CMD
              run: cousay -f dragon "Run for cover, I am a DRAGON.... RAWR" >> dragon.txt

            - name: List file exist
              run : grep -i "dragon" dragon.txt
              
            - name: Read file
              run: cat dragon.md

            - name: list repo files
              run: ls -ltra